import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular CLI and Bootstrap';
  description = 'HTML5 boiler-plate using Bootstrap and Font Awesome in an app generated by Angular CLI.';
}
